{
  "cve_id": "CVE-2020-7598",
  "alias": "PyYAML unsafe_load RCE",
  "cvss_score": 9.8,
  "published_date": "2020-02-27",
  "affected_software": {
    "name": "PyYAML",
    "versions": [
      "<5.3"
    ]
  },
  "patched_versions": [
    "5.3+"
  ],
  "cwe": "CWE-502",
  "mitre_attack_ids": [
    "T1059",
    "T1203"
  ],
  "risk_profile": {
    "exploitability": 9,
    "impact": 9,
    "detection_difficulty": 3,
    "remediation_complexity": 2,
    "known_exploits": true
  }
}